
name: Doxygen Deploy

# Controls when the action will run. 
# Triggers the workflow on push event for the `master` and `develop` branch
# Note that the Deploy action will update the branch `gh-pages`.
# The webpage `https://nimblesm.github.io/NimbleSM` is linked to the branch `gh-pages`
on:
  push:
    branches:
    - master
    - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./docs/doxygen/doxygen.conf" # default is ./Doxyfile
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Default Doxyfile build documentation to html directory. 
        # Change the directory if changes in Doxyfile
        publish_dir: "./doxygen/html"
        publish_branch: gh-pages
