name: ubuntu-arborx-mpi-openmp
#
# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-18.04
    env:
      OMP_NUM_THREADS: 4
      CMAKE_BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        shell: bash
        run: |
             sudo apt-get update -y -qq
             sudo apt-get install -y libblas-dev liblapack-dev
             sudo apt-get install -y libmetis-dev
             sudo apt-get install -y openmpi-bin libopenmpi-dev
             sudo apt-get install -y netcdf-bin libnetcdf-dev
             sudo apt-get install -y libhdf5-serial-dev libhdf5-mpich-dev
             sudo add-apt-repository ppa:nschloe/seacas-nightly
             sudo apt-get update -y -qq
             sudo apt-get install -y seacas-bin libseacas-dev
             git clone https://github.com/kokkos/kokkos.git
             cd kokkos
             mkdir build && cd build
             cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=ON \
                   -DCMAKE_INSTALL_PREFIX="/usr/"
             make && sudo make install
             cd ../..
             git clone https://github.com/arborx/arborx.git
             cd arborx
             mkdir build && cd build
             cmake .. -DCMAKE_BUILD_TYPE=Release \
                      -DKokkos_ENABLE_OPENMP=ON \
                      -DARBORX_ENABLE_MPI=ON \
                      -DCMAKE_INSTALL_PREFIX="/usr/"
             make && sudo make install
      - name: cmake
        shell: bash
        run: |
           mkdir build && cd build
           cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" \
                 -Dexodus_INCLUDE_DIR="/usr/include" \
                 -Dexodus_LIBRARY="/usr/lib/x86_64-linux-gnu/libexodus.so" \
                 -DNimbleSM_ENABLE_KOKKOS=ON \
                 -DNimbleSM_ENABLE_ARBORX=ON \
                 -DNimbleSM_ENABLE_MPI=ON \
                 -DNimbleSM_ENABLE_GTEST=ON \
                 ..
      - name: compile
        run: cmake --build build
      - name: test
        run: |
           cd build
           export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH}"
           make -j4 test
      - name: Upload log files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: log-files
          path: ./**/*.log
